-- ============================================================================================================================
-- DATA QUALITY CHECKS : Gold Layer
-- ============================================================================================================================
-- Purpose   : Validate all three Gold views after every Silver refresh.
--             Each check prints a label, runs a query, and returns a result set.
--             Any count > 0  must be investigated before publishing reports.
-- Sections  :
--             1. gold.dim_customers    – 5 checks
--             2. gold.dim_products     – 5 checks
--             3. gold.fact_sales       – 5 checks
--             4. Join integrity        – 3 checks  (fact <-> both dims)
-- How to run: Execute this script in full after  EXEC silver.load_silver
-- ============================================================================================================================


-- ============================================================
--  SECTION 1 :  gold.dim_customers
-- ============================================================
PRINT '============================================================';
PRINT ' Quality Checks  >>  gold.dim_customers';
PRINT '============================================================';
PRINT '';

-- ------------------------------------------------------------
-- [1.1]  NULL check  –  customer_key
-- Expectation : 0
-- Why         : customer_key is the surrogate PK generated by ROW_NUMBER().
--               A NULL here means cst_id was NULL in Silver (should have been filtered).
-- ------------------------------------------------------------
PRINT '>> [1.1]  [NULL]  customer_key';
SELECT
    COUNT(*) AS null_customer_key
FROM gold.dim_customers
WHERE customer_key IS NULL;

-- ------------------------------------------------------------
-- [1.2]  Duplicate check  –  customer_key
-- Expectation : 0 rows returned
-- Why         : customer_key is the PK of this dimension.
--               Any duplicate would cause row fan-out when fact_sales joins it.
-- ------------------------------------------------------------
PRINT '>> [1.2]  [DUPLICATE]  customer_key';
SELECT
    customer_key,
    COUNT(*) AS duplicate_count
FROM gold.dim_customers
GROUP BY customer_key
HAVING COUNT(*) > 1;

-- ------------------------------------------------------------
-- [1.3]  Domain check  –  gender
-- Expectation : 0 rows returned
-- Why         : After Silver cleaning and the CASE fallback logic in the view,
--               only three values are valid. Anything else is an unhandled source code.
-- ------------------------------------------------------------
PRINT '>> [1.3]  [DOMAIN]  gender  (Male | Female | N/A only)';
SELECT
    gender,
    COUNT(*) AS cnt
FROM gold.dim_customers
WHERE gender NOT IN ('Male', 'Female', 'N/A')
GROUP BY gender;

-- ------------------------------------------------------------
-- [1.4]  Domain check  –  marital_status
-- Expectation : 0 rows returned
-- Why         : Silver expanded M/S codes to full labels.
--               Any raw code remaining means the CASE in the SP was bypassed.
-- ------------------------------------------------------------
PRINT '>> [1.4]  [DOMAIN]  marital_status  (Married | Single | N/A only)';
SELECT
    marital_status,
    COUNT(*) AS cnt
FROM gold.dim_customers
WHERE marital_status NOT IN ('Married', 'Single', 'N/A')
GROUP BY marital_status;

-- ------------------------------------------------------------
-- [1.5]  Date check  –  birth_date
-- Expectation : 0
-- Why         : Future birthdates were set to NULL in Silver (16 rows corrected).
--               Any future date here means the Silver fix is not working.
-- ------------------------------------------------------------
PRINT '>> [1.5]  [DATE]  birth_date must not be in the future';
SELECT
    COUNT(*) AS future_birth_date_rows
FROM gold.dim_customers
WHERE birth_date > CAST(GETDATE() AS DATE);

PRINT '';


-- ============================================================
--  SECTION 2 :  gold.dim_products
-- ============================================================
PRINT '============================================================';
PRINT ' Quality Checks  >>  gold.dim_products';
PRINT '============================================================';
PRINT '';

-- ------------------------------------------------------------
-- [2.1]  NULL check  –  product_key
-- Expectation : 0
-- Why         : product_key is the surrogate PK generated by ROW_NUMBER().
--               A NULL means prd_id was NULL in Silver which should never happen.
-- ------------------------------------------------------------
PRINT '>> [2.1]  [NULL]  product_key';
SELECT
    COUNT(*) AS null_product_key
FROM gold.dim_products
WHERE product_key IS NULL;

-- ------------------------------------------------------------
-- [2.2]  Duplicate check  –  product_key
-- Expectation : 0 rows returned
-- Why         : product_key is the PK of this dimension.
--               Any duplicate would cause fan-out when fact_sales joins it.
-- ------------------------------------------------------------
PRINT '>> [2.2]  [DUPLICATE]  product_key';
SELECT
    product_key,
    COUNT(*) AS duplicate_count
FROM gold.dim_products
GROUP BY product_key
HAVING COUNT(*) > 1;

-- ------------------------------------------------------------
-- [2.3]  Domain check  –  product_line
-- Expectation : 0 rows returned
-- Why         : Silver expanded R/M/S/T codes to full labels with N/A fallback.
--               Any unrecognised value means a new source code is not handled.
-- ------------------------------------------------------------
PRINT '>> [2.3]  [DOMAIN]  product_line  (Road | Mountain | Other Sale | Touring | N/A only)';
SELECT
    product_line,
    COUNT(*) AS cnt
FROM gold.dim_products
WHERE product_line NOT IN ('Road', 'Mountain', 'Other Sale', 'Touring', 'N/A')
GROUP BY product_line;

-- ------------------------------------------------------------
-- [2.4]  Range check  –  product_cost
-- Expectation : 0
-- Why         : NULL cost was replaced with 0 in Silver.
--               Negative cost is logically invalid for a product catalogue.
-- ------------------------------------------------------------
PRINT '>> [2.4]  [RANGE]  product_cost must be >= 0';
SELECT
    COUNT(*) AS negative_cost_rows
FROM gold.dim_products
WHERE product_cost < 0;

-- ------------------------------------------------------------
-- [2.5]  Informational  –  products without ERP category
-- Expectation : <= 7  (known gap – 7 products have no ERP category match)
-- Why         : Monitors growth of unmapped products. If count grows beyond 7
--               new products are arriving without ERP category records.
-- ------------------------------------------------------------
PRINT '>> [2.5]  [INFO]  products with no ERP category mapping  (expected <= 7)';
SELECT
    COUNT(*) AS products_without_category
FROM gold.dim_products
WHERE category IS NULL;

PRINT '';


-- ============================================================
--  SECTION 3 :  gold.fact_sales
-- ============================================================
PRINT '============================================================';
PRINT ' Quality Checks  >>  gold.fact_sales';
PRINT '============================================================';
PRINT '';

-- ------------------------------------------------------------
-- [3.1]  NULL check  –  surrogate foreign keys
-- Expectation : 0
-- Why         : Both FKs must be populated on every row.
--               A NULL customer_key means a sale has no customer.
--               A NULL product_key  means a sale has no product.
-- ------------------------------------------------------------
PRINT '>> [3.1]  [NULL]  customer_key and product_key';
SELECT
    COUNT(*) AS null_fk_rows
FROM gold.fact_sales
WHERE customer_key IS NULL
   OR product_key  IS NULL;

-- ------------------------------------------------------------
-- [3.2]  Range check  –  measures must be positive
-- Expectation : 0
-- Why         : Negative prices and sales amounts were corrected in Silver via ABS().
--               Any negative value remaining means the Silver fix did not apply.
-- ------------------------------------------------------------
PRINT '>> [3.2]  [RANGE]  sales_amount and unit_price must be > 0';
SELECT
    COUNT(*) AS negative_measure_rows
FROM gold.fact_sales
WHERE sales_amount < 0
   OR unit_price   < 0;

-- ------------------------------------------------------------
-- [3.3]  Consistency check  –  sales_amount = quantity * unit_price
-- Expectation : 0
-- Why         : Inconsistencies (19 rows in source) were recalculated in Silver.
--               Any remaining mismatch means the Silver SP logic has a gap.
-- Tolerance   : +-0.01 to allow for floating point rounding.
-- ------------------------------------------------------------
PRINT '>> [3.3]  [CONSISTENCY]  sales_amount = quantity * unit_price  (tolerance +-0.01)';
SELECT
    COUNT(*) AS inconsistent_rows
FROM gold.fact_sales
WHERE ABS(sales_amount - quantity * unit_price) > 0.01
  AND sales_amount IS NOT NULL
  AND unit_price   IS NOT NULL
  AND quantity     IS NOT NULL;

-- ------------------------------------------------------------
-- [3.4]  Date check  –  order_date must be <= ship_date and <= due_date
-- Expectation : 0
-- Why         : An order cannot be shipped or due before it was placed.
--               This is a logical impossibility indicating bad source data.
-- ------------------------------------------------------------
PRINT '>> [3.4]  [DATE]  order_date <= ship_date  and  order_date <= due_date';
SELECT
    COUNT(*) AS invalid_date_sequence_rows
FROM gold.fact_sales
WHERE (order_date > ship_date AND ship_date IS NOT NULL)
   OR (order_date > due_date  AND due_date  IS NOT NULL);

-- ------------------------------------------------------------
-- [3.5]  Informational  –  fact summary
-- Expectation : 60,398 rows | date range and total sales look sensible
-- Why         : Quick sanity check after every Silver refresh to confirm
--               no rows were dropped or duplicated during the load.
-- ------------------------------------------------------------
PRINT '>> [3.5]  [INFO]  fact_sales row count and date range';
SELECT
    COUNT(*)          AS total_rows,
    MIN(order_date)   AS earliest_order_date,
    MAX(order_date)   AS latest_order_date,
    SUM(sales_amount) AS total_sales_amount
FROM gold.fact_sales;

PRINT '';


-- ============================================================
--  SECTION 4 :  JOIN INTEGRITY  –  fact_sales <-> dimensions
-- ============================================================
PRINT '============================================================';
PRINT ' Join Integrity Checks  >>  fact_sales <-> dims';
PRINT '============================================================';
PRINT '';

-- ------------------------------------------------------------
-- [4.1]  Referential integrity  –  customer_key
-- Expectation : 0
-- Why         : Every customer_key in fact_sales must resolve in dim_customers.
--               An orphaned key means a customer was not loaded into Silver
--               or the ROW_NUMBER surrogate key is inconsistent between views.
-- ------------------------------------------------------------
PRINT '>> [4.1]  [REFERENTIAL]  fact_sales.customer_key -> dim_customers.customer_key';
SELECT
    COUNT(*) AS orphaned_customer_keys
FROM      gold.fact_sales     f
LEFT JOIN gold.dim_customers  dc  ON f.customer_key = dc.customer_key
WHERE dc.customer_key IS NULL;

-- ------------------------------------------------------------
-- [4.2]  Referential integrity  –  product_key
-- Expectation : 0
-- Why         : Every product_key in fact_sales must resolve in dim_products.
--               An orphaned key means the active-only product join missed a product
--               or the Silver product data is incomplete.
-- ------------------------------------------------------------
PRINT '>> [4.2]  [REFERENTIAL]  fact_sales.product_key -> dim_products.product_key';
SELECT
    COUNT(*) AS orphaned_product_keys
FROM      gold.fact_sales     f
LEFT JOIN gold.dim_products   dp  ON f.product_key = dp.product_key
WHERE dp.product_key IS NULL;

-- ------------------------------------------------------------
-- [4.3]  Row count preservation  –  no fan-out after joining both dims
-- Expectation : row_difference = 0
-- Why         : Joining fact to both dimensions must not multiply or lose rows.
--               A positive difference means a dim join created duplicates (fan-out).
--               A negative difference means rows were lost due to an INNER JOIN effect.
-- ------------------------------------------------------------
PRINT '>> [4.3]  [ROW COUNT]  no fan-out or row loss after joining both dimensions';
SELECT
    (SELECT COUNT(*) FROM gold.fact_sales)                              AS fact_rows,

    (SELECT COUNT(*)
     FROM        gold.fact_sales     f
     LEFT JOIN   gold.dim_customers  dc  ON f.customer_key = dc.customer_key
     LEFT JOIN   gold.dim_products   dp  ON f.product_key  = dp.product_key
    )                                                                   AS rows_after_join,

    (SELECT COUNT(*) FROM gold.fact_sales) -
    (SELECT COUNT(*)
     FROM        gold.fact_sales     f
     LEFT JOIN   gold.dim_customers  dc  ON f.customer_key = dc.customer_key
     LEFT JOIN   gold.dim_products   dp  ON f.product_key  = dp.product_key
    )                                                                   AS row_difference;

PRINT '';
PRINT '============================================================';
PRINT ' Gold Layer Quality Checks  -  COMPLETE';
PRINT ' Any result with count > 0 must be reviewed before reporting.';
PRINT '============================================================';
